"""empty message

Revision ID: 94641b65b8d0
Revises: cefa58a335b3
Create Date: 2025-05-12 11:05:15.389139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94641b65b8d0'
down_revision = 'cefa58a335b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
