"""empty message

Revision ID: ef918ff69afe
Revises: 94641b65b8d0
Create Date: 2025-05-12 11:13:06.609006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef918ff69afe'
down_revision = '94641b65b8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('employees_departament_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('departament_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departament_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employees_departament_id_fkey', 'departments', ['departament_id'], ['id'])
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
